{{- if .Values.ingress.traefikEnabled}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-rebom-web-ingressroute
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`{{ .Values.ingress.host}}`)
    kind: Rule
    services:
    - name: {{ .Release.Name }}-rebom-frontend-service
      port: 80
    middlewares:
      - name: {{ .Release.Name }}-rebom-redirect
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-rebom-websecure-ingressroute
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ .Values.ingress.host}}`)
    kind: Rule
    services:
    - name: {{ .Release.Name }}-rebom-frontend-service
      port: 80
  tls:
    certResolver: le
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-rebom-redirect
  namespace: {{ .Release.Namespace }}
spec:
  redirectScheme:
    scheme: https
{{- end}}