{{- if .Values.ingress.minimalIngressEnabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-rebom-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rebom.labels" . | nindent 4 }}
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-rebom-frontend-service
            port:
              number: 80
{{- end }}