{{- if .Values.enabled}}
{{- if .Values.postgres.defaultSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rebom-pgpassword
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rebom.labels" . | nindent 4 }}
type: Opaque
data:
  password: cGFzc3dvcmQ=
{{- end }}
{{- end}}