enabled: true
backend:
  image: registry.relizahub.com/library/rebom-backend
  replicaCount: 1
  regcred: none
  oci:
    enabled: false
    serviceHost: http://[::1]:8083/
    registryHost: registry
    registryNamespace: namespace
frontend:
  image: registry.relizahub.com/library/rebom-frontend
  replicaCount: 1
  regcred: none
postgres:
  image: postgres:16
  defaultSecret: true
  replicaCount: 1
  storage: 5Gi
flyway:
  image: flyway/flyway:8.4.4-alpine
ingress:
  minimalIngressEnabled: true
  traefikEnabled: false
  host: localhost

ecr-regcred:
  enabled: false