on: [push]

name: Build Docker Image And Submit Metadata To Reliza Hub

jobs:
  build-backend:
    name: Build And Push Backend
    runs-on: ubuntu-latest
    steps:
      - name: RelizaHub Build And Submit Release metadata action
        uses: relizaio/reliza-docker-action@1.4
        with:
          registry_username: ${{ secrets.DOCKER_LOGIN }}
          registry_password: ${{ secrets.DOCKER_TOKEN }}
          registry_host: registry.relizahub.com
          image_namespace: registry.relizahub.com/library
          image_name: rebom-backend
          reliza_api_id: ${{ secrets.RELIZA_BACKEND_API_ID }}
          reliza_api_key: ${{ secrets.RELIZA_BACKEND_API_KEY }}
          path: backend
  build-frontend:
    name: Build And Push Frontend
    runs-on: ubuntu-latest
    steps:
      - name: RelizaHub Build And Submit Release metadata action
        uses: relizaio/reliza-docker-action@1.4
        with:
          registry_username: ${{ secrets.DOCKER_LOGIN }}
          registry_password: ${{ secrets.DOCKER_TOKEN }}
          registry_host: registry.relizahub.com
          image_namespace: registry.relizahub.com/library
          image_name: rebom-frontend
          reliza_api_id: ${{ secrets.RELIZA_FRONTEND_API_ID }}
          reliza_api_key: ${{ secrets.RELIZA_FRONTEND_API_KEY }}
          path: frontend
  build-helm:
    name: Build And Push Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: RelizaHub Build And Submit Release metadata action
        uses: relizaio/reliza-helm-action@1.6
        with:
          registry_username: ${{ secrets.DOCKER_LOGIN }}
          registry_password: ${{ secrets.DOCKER_TOKEN }}
          registry_host: https://registry.relizahub.com/chartrepo/library/
          helm_chart_name: rebom
          reliza_api_id: ${{ secrets.RELIZA_HELM_API_ID }}
          reliza_api_key: ${{ secrets.RELIZA_HELM_API_KEY }}
          path: helm
          registry_type: CHARTMEUSEUM
